[package]
name = "ts"
author = "https://github.com/rathrio"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ts"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
regex = "1"
lazy_static = "1.4.0"
clap = { version = "3.1.6", features = ["derive"] }
colored = "2"
